In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


In [2]:
#cargar archivo desde seaborn 
df=pd.read_csv('Boston_Limpio_Procesado.csv')
df.head(5)

id                         listing_url       scrape_id last_scraped  \
0   3781   https://www.airbnb.com/rooms/3781  20241220045258   2024-12-20   
1   5506   https://www.airbnb.com/rooms/5506  20241220045258   2024-12-20   
2  10986  https://www.airbnb.com/rooms/10986  20241220045258   2024-12-20   
3  29765  https://www.airbnb.com/rooms/29765  20241220045258   2024-12-20   
4  45987  https://www.airbnb.com/rooms/45987  20241220045258   2024-12-20   

            source                                               name  \
0  previous scrape                          HARBORSIDE-Walk to subway   
1      city scrape     ** Fort Hill Inn Private! Minutes to center!**   
2  previous scrape  North End (Waterfront area)  CLOSE TO MGH & SU...   
3      city scrape                               Moroccan Decor Suite   
4      city scrape                                      Garden Studio   

                                         description  \
0  Fully separate apartment in a two apartment bu...   
1  Private guest room with private bath, You do n...   
2  Chic furnished studio apartment is located on ...   
3  The apartment is a unique space that offers a ...   
4  Light and spacious garden studio apartment has...   

                               neighborhood_overview  \
0  Mostly quiet ( no loud music, no crowed sidewa...   
1  Peaceful, Architecturally interesting, histori...   
2                                                NaN   
3  Boston's oldest and most historic neighborhood...   
4                               Historical and safe.   

                                         picture_url  host_id  ...  \
0  https://a0.muscache.com/pictures/24670/b2de044...     4804  ...   
1  https://a0.muscache.com/pictures/miso/Hosting-...     8229  ...   
2  https://a0.muscache.com/pictures/46994/567b606...    38997  ...   
3  https://a0.muscache.com/pictures/621420/77d899...   128280  ...   
4  https://a0.muscache.com/pictures/7a7d6642-f493...   205107  ...   

  review_scores_communication review_scores_location review_scores_value  \
0                        4.96                   4.85                4.88   
1                        4.89                   4.56                4.76   
2                        5.00                   5.00                4.00   
3                        4.97                   4.81                4.94   
4                        4.71                   4.83                4.53   

      license instant_bookable calculated_host_listings_count  \
0         NaN                0                              1   
1  STR-490093                0                             10   
2         NaN                0                             13   
3  STR-454024                0                              1   
4  STR-409822                0                              1   

  calculated_host_listings_count_entire_homes  \
0                                           1   
1                                          10   
2                                          13   
3                                           1   
4                                           1   

  calculated_host_listings_count_private_rooms  \
0                                            0   
1                                            0   
2                                            0   
3                                            0   
4                                            0   

   calculated_host_listings_count_shared_rooms reviews_per_month  
0                                            0              0.23  
1                                            0              0.69  
2                                            0              0.09  
3                                            0              0.58  
4                                            0              0.81  

[5 rows x 73 columns]

In [3]:
#cargar archivo csv desde seaboarn
#df=sns.load_dataset(name='titanic')
#df.head(5)

In [4]:
# Relleno de valores nulos 

df = df.fillna(method="bfill")
df = df.fillna(method="ffill")

C:\Users\ghseb\AppData\Local\Temp\ipykernel_21744\2761572045.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method="bfill")
C:\Users\ghseb\AppData\Local\Temp\ipykernel_21744\2761572045.py:4: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method="ffill")


In [5]:
# Asegúrate de que tienes un DataFrame llamado 'df'
print(df.columns)

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'latitude', 'longitude', 'property_type',
       'room_type', 'accommodates', 'bathrooms', 'bathrooms_text', 'bedrooms',
       'beds', 'amenities', 'price', 'minimum_nights', 'maximum_nights',
       'minimum_minimum_nights', 'maximum_minimum_nights',
       'minimum_maximum_nights', 'maximum_maximum_nights',
       'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'has_availability',
       'availability_3

In [6]:
#f1=df

In [7]:
# Imprimir las columnas que son de tipo numérico
numeric_columns = df.select_dtypes(include=['number']).columns
print(numeric_columns)

Index(['id', 'scrape_id', 'host_id', 'host_is_superhost',
       'host_listings_count', 'host_total_listings_count',
       'host_has_profile_pic', 'host_identity_verified', 'latitude',
       'longitude', 'accommodates', 'bathrooms', 'bedrooms', 'beds', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'availability_30', 'availability_60',
       'availability_90', 'availability_365', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_li

In [8]:
df['price'] = df['price'].astype(str).str.replace(r'[\$,]', '', regex=True)
df['price'] = pd.to_numeric(df['price'], errors='coerce').fillna(0)

In [9]:
print(df['price'].head())

0    135.0
1    112.0
2    135.0
3    243.0
4    100.0
Name: price, dtype: float64


In [10]:
#convertimos string a tipos numéricos
#df['host_is_superhost'] = df['host_is_superhost'].replace({'f': 0, 't': 1})

In [11]:
# Convertir variables categóricas a numéricas
#df['host_is_superhost'] = df['host_is_superhost'].map({'f': 0, 't': 1})
#df['host_has_profile_pic'] = df['host_has_profile_pic'].map({'f': 0, 't': 1})
#df['host_identity_verified'] = df['host_identity_verified'].map({'f': 0, 't': 1})
#df['instant_bookable'] = df['instant_bookable'].map({'f': 0, 't': 1})

In [12]:
print(df['host_is_superhost'].head(10))

0    1.0
1    1.0
2    0.0
3    0.0
4    1.0
5    1.0
6    0.0
7    0.0
8    1.0
9    1.0
Name: host_is_superhost, dtype: float64


In [13]:
# Declaramos las variables dependientes e independientes para la regresión logística
#Vars_Indep = df[['pclass', 'age', 'fare']]
#Var_Dep = df['alive']
Vars_Indep1= df[['price', 'accommodates']]
Var_Dep1= df['host_is_superhost']

# Caso 1
Vars_Indep2 = df[['price', 'accommodates']]
Var_Dep2 = df['host_is_superhost']

# Caso 2
Vars_Indep3 = df[['bedrooms', 'beds']]
Var_Dep3 = df['instant_bookable']

# Caso 3
Vars_Indep4 = df[['price', 'availability_90']]
Var_Dep4 = df['host_identity_verified']

# Caso 4
Vars_Indep5 = df[['minimum_nights', 'reviews_per_month']]
Var_Dep5 = df['host_is_superhost']

# Caso 5
Vars_Indep6 = df[['accommodates', 'bathrooms']]
Var_Dep6 = df['instant_bookable']

# Caso 6
Vars_Indep7 = df[['price', 'number_of_reviews']]
Var_Dep7 = df['host_identity_verified']

# Caso 7
Vars_Indep8 = df[['beds', 'availability_30']]
Var_Dep8 = df['host_is_superhost']

# Caso 8
Vars_Indep9 = df[['price', 'review_scores_rating']]
Var_Dep9 = df['instant_bookable']

# Caso 9
Vars_Indep10 = df[['reviews_per_month', 'bedrooms']]
Var_Dep10 = df['host_identity_verified']

In [14]:
# Redefinimos las variables
X = Vars_Indep1
y = Var_Dep1
x2 = Vars_Indep2
y2 = Var_Dep2           
x3 = Vars_Indep3
y3 = Var_Dep3
x4 = Vars_Indep4
y4 = Var_Dep4
x5 = Vars_Indep5
y5 = Var_Dep5
x6 = Vars_Indep6
y6 = Var_Dep6
x7 = Vars_Indep7
y7 = Var_Dep7
x8 = Vars_Indep8
y8 = Var_Dep8
x9 = Vars_Indep9
y9 = Var_Dep9
x10 = Vars_Indep10
y10 = Var_Dep10


In [15]:
# Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)



# Dividir cada conjunto de variables independientes y dependientes
X1_train, X1_test, y1_train, y1_test = train_test_split(X, y, test_size=0.3, random_state=None)
X2_train, X2_test, y2_train, y2_test = train_test_split(x2, y2, test_size=0.3, random_state=None)
X3_train, X3_test, y3_train, y3_test = train_test_split(x3, y3, test_size=0.3, random_state=None)
X4_train, X4_test, y4_train, y4_test = train_test_split(x4, y4, test_size=0.3, random_state=None)
X5_train, X5_test, y5_train, y5_test = train_test_split(x5, y5, test_size=0.3, random_state=None)
X6_train, X6_test, y6_train, y6_test = train_test_split(x6, y6, test_size=0.3, random_state=None)
X7_train, X7_test, y7_train, y7_test = train_test_split(x7, y7, test_size=0.3, random_state=None)
X8_train, X8_test, y8_train, y8_test = train_test_split(x8, y8, test_size=0.3, random_state=None)
X9_train, X9_test, y9_train, y9_test = train_test_split(x9, y9, test_size=0.3, random_state=None)
X10_train, X10_test, y10_train, y10_test = train_test_split(x10, y10, test_size=0.3, random_state=None)

In [16]:
#se escalan todos los datos
escalar = StandardScaler()

In [17]:
# Para realizar el escalamiento de las variables "X" tanto de entrenamiento como de prueba, utilizaremos
#X_train = escalar.fit_transform(X_train)
#X_test = escalar.transform(X_test)

# Escalamos cada conjunto de datos (X_train y X_test) para las 10 variables
# --- Conjunto 1 ---
X1_train = escalar.fit_transform(X1_train)  
X1_test = escalar.transform(X1_test)       

# --- Conjunto 2 ---
X2_train = escalar.fit_transform(X2_train)
X2_test = escalar.transform(X2_test)

# --- Conjunto 3 ---
X3_train = escalar.fit_transform(X3_train)
X3_test = escalar.transform(X3_test)

# --- Conjunto 4 ---
X4_train = escalar.fit_transform(X4_train)
X4_test = escalar.transform(X4_test)

# --- Conjunto 5 ---
X5_train = escalar.fit_transform(X5_train)
X5_test = escalar.transform(X5_test)

# --- Conjunto 6 ---
X6_train = escalar.fit_transform(X6_train)
X6_test = escalar.transform(X6_test)

# --- Conjunto 7 ---
X7_train = escalar.fit_transform(X7_train)
X7_test = escalar.transform(X7_test)

# --- Conjunto 8 ---
X8_train = escalar.fit_transform(X8_train)
X8_test = escalar.transform(X8_test)

# --- Conjunto 9 ---
X9_train = escalar.fit_transform(X9_train)
X9_test = escalar.transform(X9_test)

# --- Conjunto 10 ---
X10_train = escalar.fit_transform(X10_train)
X10_test = escalar.transform(X10_test)

In [18]:
#definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()    

In [19]:
#entremanos el modelo   
#algoritmo.fit(X_train, y_train) 

# Entrenamos los 10 modelos uno por uno:

# Modelo 1
algoritmo.fit(X1_train, y1_train)

# Modelo 2
algoritmo.fit(X2_train, y2_train)

# Modelo 3
algoritmo.fit(X3_train, y3_train)

# Modelo 4
algoritmo.fit(X4_train, y4_train)

# Modelo 5
algoritmo.fit(X5_train, y5_train)

# Modelo 6
algoritmo.fit(X6_train, y6_train)

# Modelo 7
algoritmo.fit(X7_train, y7_train)

# Modelo 8
algoritmo.fit(X8_train, y8_train)

# Modelo 9
algoritmo.fit(X9_train, y9_train)

# Modelo 10
algoritmo.fit(X10_train, y10_train)

LogisticRegression()

In [20]:
print("Dimensiones del conjunto de entrenamiento:", X1_train.shape)
print("Dimensiones de X1_test:", X1_test.shape)
print("Dimensiones de X2_test:", X2_test.shape)
# Repite para los demás conjuntos de prueba

Dimensiones del conjunto de entrenamiento: (825, 2)
Dimensiones de X1_test: (354, 2)
Dimensiones de X2_test: (354, 2)


In [21]:
# Selecciona las primeras 2 columnas de cada conjunto de prueba
#X1_test = X1_test[:, :2]
#X2_test = X2_test[:, :2]
#X3_test = X3_test[:, :2]
#X4_test = X4_test[:, :2]
#X5_test = X5_test[:, :2]
#X6_test = X6_test[:, :2]
#X7_test = X7_test[:, :2]
#X8_test = X8_test[:, :2]
#X9_test = X9_test[:, :2]
#X10_test = X10_test[:, :2]

In [22]:
#realizamos una predicción  
#y_pred = algoritmo.predict(X_test)
#y_pred


# Predicción Modelo 1
y1_pred = algoritmo.predict(X1_test)

# Predicción Modelo 2
y2_pred = algoritmo.predict(X2_test)

# Predicción Modelo 3
y3_pred = algoritmo.predict(X3_test)

# Predicción Modelo 4
y4_pred = algoritmo.predict(X4_test)

# Predicción Modelo 5
y5_pred = algoritmo.predict(X5_test)

# Predicción Modelo 6
y6_pred = algoritmo.predict(X6_test)

# Predicción Modelo 7
y7_pred = algoritmo.predict(X7_test)

# Predicción Modelo 8
y8_pred = algoritmo.predict(X8_test)

# Predicción Modelo 9
y9_pred = algoritmo.predict(X9_test)

# Predicción Modelo 10
y10_pred = algoritmo.predict(X10_test)

# Imprimir las predicciones de cada modelo
print("Predicciones Modelo 1:", y1_pred)    
print("Predicciones Modelo 2:", y2_pred)
print("Predicciones Modelo 3:", y3_pred)
print("Predicciones Modelo 4:", y4_pred)
print("Predicciones Modelo 5:", y5_pred)
print("Predicciones Modelo 6:", y6_pred)
print("Predicciones Modelo 7:", y7_pred)
print("Predicciones Modelo 8:", y8_pred)
print("Predicciones Modelo 9:", y9_pred)
print("Predicciones Modelo 10:", y10_pred)


Predicciones Modelo 1: [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
Predicciones Modelo 2: [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1

In [23]:

# Convierte las etiquetas reales a números
#y1_test = [0 if label == 'f' else 1 for label in y1_test]
#y2_test = [0 if label == 'f' else 1 for label in y2_test]
#y3_test = [0 if label == 'f' else 1 for label in y3_test]
#y4_test = [0 if label == 'f' else 1 for label in y4_test]
##y5_test = [0 if label == 'f' else 1 for label in y5_test]
#y6_test = [0 if label == 'f' else 1 for label in y6_test]
#y7_test = [0 if label == 'f' else 1 for label in y7_test]
#y8_test = [0 if label == 'f' else 1 for label in y8_test]
#y9_test = [0 if label == 'f' else 1 for label in y9_test]
#y10_test = [0 if label == 'f' else 1 for label in y10_test]


In [24]:
print("Etiquetas reales (y1_test):", y1_test[:10])
print("Etiquetas predichas (y1_pred):", y1_pred[:10])

Etiquetas reales (y1_test): 551     1.0
296     0.0
1013    0.0
321     1.0
393     1.0
394     0.0
128     1.0
629     0.0
453     0.0
14      0.0
Name: host_is_superhost, dtype: float64
Etiquetas predichas (y1_pred): [1 1 1 1 1 1 1 1 1 1]


In [25]:
#verifico la matriz de confusión
from sklearn.metrics import confusion_matrix
#matriz = confusion_matrix(y_test, y_pred)
#print('Matriz de Confusión:')
#print(matriz)


#from sklearn.metrics import confusion_matrix

# Matriz de confusión para cada modelo:

# --- Modelo 1 ---
matriz1 = confusion_matrix(y1_test, y1_pred)
print('\nMatriz de Confusión Modelo 1:')
print(matriz1)

# --- Modelo 2 ---
matriz2 = confusion_matrix(y2_test, y2_pred)
print('\nMatriz de Confusión Modelo 2:')
print(matriz2)

# --- Modelo 3 ---
matriz3 = confusion_matrix(y3_test, y3_pred)
print('\nMatriz de Confusión Modelo 3:')
print(matriz3)

# --- Modelo 4 ---
matriz4 = confusion_matrix(y4_test, y4_pred)
print('\nMatriz de Confusión Modelo 4:')
print(matriz4)

# --- Modelo 5 ---
matriz5 = confusion_matrix(y5_test, y5_pred)
print('\nMatriz de Confusión Modelo 5:')
print(matriz5)

# --- Modelo 6 ---
matriz6 = confusion_matrix(y6_test, y6_pred)
print('\nMatriz de Confusión Modelo 6:')
print(matriz6)

# --- Modelo 7 ---
matriz7 = confusion_matrix(y7_test, y7_pred)
print('\nMatriz de Confusión Modelo 7:')
print(matriz7)

# --- Modelo 8 ---
matriz8 = confusion_matrix(y8_test, y8_pred)
print('\nMatriz de Confusión Modelo 8:')
print(matriz8)

# --- Modelo 9 ---
matriz9 = confusion_matrix(y9_test, y9_pred)
print('\nMatriz de Confusión Modelo 9:')
print(matriz9)

# --- Modelo 10 ---
matriz10 = confusion_matrix(y10_test, y10_pred)
print('\nMatriz de Confusión Modelo 10:')
print(matriz10)


Matriz de Confusión Modelo 1:
[[  0 223]
 [  0 131]]

Matriz de Confusión Modelo 2:
[[  0 230]
 [  0 124]]

Matriz de Confusión Modelo 3:
[[  0 221]
 [  0 133]]

Matriz de Confusión Modelo 4:
[[  0  36]
 [  0 318]]

Matriz de Confusión Modelo 5:
[[  0 220]
 [  0 134]]

Matriz de Confusión Modelo 6:
[[  0 229]
 [  0 125]]

Matriz de Confusión Modelo 7:
[[  0  36]
 [  0 318]]

Matriz de Confusión Modelo 8:
[[  0 229]
 [  0 125]]

Matriz de Confusión Modelo 9:
[[  0 234]
 [  0 120]]

Matriz de Confusión Modelo 10:
[[  0  37]
 [  0 317]]


In [27]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

# Configura el modelo con balanceo de clases y ajuste de umbral
modelo = LogisticRegression(class_weight='balanced', random_state=42, max_iter=1000)

# Lista de tus pares (X_train, X_test, y_train, y_test) para los 10 modelos
datos_modelos = [
    (X1_train, X1_test, y1_train, y1_test),
    (X2_train, X2_test, y2_train, y2_test),
    (X3_train, X3_test, y3_train, y3_test),
    (X4_train, X4_test, y4_train, y4_test),
    (X5_train, X5_test, y5_train, y5_test),
    (X6_train, X6_test, y6_train, y6_test),
    (X7_train, X7_test, y7_train, y7_test),
    (X8_train, X8_test, y8_train, y8_test),
    (X9_train, X9_test, y9_train, y9_test),
    (X10_train, X10_test, y10_train, y10_test)
]

# Corregir las matrices de confusión para cada modelo
for i, (X_train, X_test, y_train, y_test) in enumerate(datos_modelos, start=1):
    modelo.fit(X_train, y_train)
    
    y_pred_prob = modelo.predict_proba(X_test)[:, 1]  
    y_pred_ajustado = ['f' if prob >= 0.3 else 't' for prob in y_pred_prob]  

    # Convertir ambas listas a strings
    y_test = [str(y) for y in y_test]  
    y_pred_ajustado = [str(y) for y in y_pred_ajustado]  

    matriz = confusion_matrix(y_test, y_pred_ajustado)
    
    print(f"\n--- Matriz de Confusión Modelo {i} (Umbral=0.3) ---")
    print(matriz)


--- Matriz de Confusión Modelo 1 (Umbral=0.3) ---
[[  0   0 222   1]
 [  0   0 131   0]
 [  0   0   0   0]
 [  0   0   0   0]]

--- Matriz de Confusión Modelo 2 (Umbral=0.3) ---
[[  0   0 230]
 [  0   0 124]
 [  0   0   0]]

--- Matriz de Confusión Modelo 3 (Umbral=0.3) ---
[[  0   0 221]
 [  0   0 133]
 [  0   0   0]]

--- Matriz de Confusión Modelo 4 (Umbral=0.3) ---
[[  0   0  36]
 [  0   0 318]
 [  0   0   0]]

--- Matriz de Confusión Modelo 5 (Umbral=0.3) ---
[[  0   0 220]
 [  0   0 134]
 [  0   0   0]]

--- Matriz de Confusión Modelo 6 (Umbral=0.3) ---
[[  0   0 229]
 [  0   0 125]
 [  0   0   0]]

--- Matriz de Confusión Modelo 7 (Umbral=0.3) ---
[[  0   0  36]
 [  0   0 318]
 [  0   0   0]]

--- Matriz de Confusión Modelo 8 (Umbral=0.3) ---
[[  0   0 229]
 [  0   0 125]
 [  0   0   0]]

--- Matriz de Confusión Modelo 9 (Umbral=0.3) ---
[[  0   0 234]
 [  0   0 120]
 [  0   0   0]]

--- Matriz de Confusión Modelo 10 (Umbral=0.3) ---
[[  0   0  37]
 [  0   0 317]
 [  0   0   0]

In [28]:
y1_test = np.where(y1_test == 'No', 'f', y1_test)

In [29]:
print("Clases en y1_test:", np.unique(y1_test))
print("Clases en y1_pred:", np.unique(y1_pred))

Clases en y1_test: ['0.0' '1.0']
Clases en y1_pred: [1]


In [30]:
for i in range(1, 11):  # Del Modelo 1 al 10
    y_test = globals()[f'y{i}_test']
    y_pred = globals()[f'y{i}_pred']
    print(f"\nModelo {i} - Clases en y_test:", np.unique(y_test))
    print(f"Modelo {i} - Clases en y_pred:", np.unique(y_pred))


Modelo 1 - Clases en y_test: ['0.0' '1.0']
Modelo 1 - Clases en y_pred: [1]

Modelo 2 - Clases en y_test: [0. 1.]
Modelo 2 - Clases en y_pred: [1]

Modelo 3 - Clases en y_test: [0 1]
Modelo 3 - Clases en y_pred: [1]

Modelo 4 - Clases en y_test: [0 1]
Modelo 4 - Clases en y_pred: [1]

Modelo 5 - Clases en y_test: [0. 1.]
Modelo 5 - Clases en y_pred: [1]

Modelo 6 - Clases en y_test: [0 1]
Modelo 6 - Clases en y_pred: [1]

Modelo 7 - Clases en y_test: [0 1]
Modelo 7 - Clases en y_pred: [1]

Modelo 8 - Clases en y_test: [0. 1.]
Modelo 8 - Clases en y_pred: [1]

Modelo 9 - Clases en y_test: [0 1]
Modelo 9 - Clases en y_pred: [1]

Modelo 10 - Clases en y_test: [0 1]
Modelo 10 - Clases en y_pred: [1]


In [31]:
from sklearn.metrics import precision_score
import numpy as np

def precision_binaria(y_true, y_pred, pos_label='t'):
    """Calcula la precisión considerando solo 't' y 'f' (ignora otras clases)."""
    # Filtra solo muestras donde y_true es 't' o 'f'
    mask = np.isin(y_true, ['t', 'f'])
    y_true_bin = y_true[mask]
    y_pred_bin = y_pred[mask]
    
    # Calcula la precisión binaria
    return precision_score(y_true_bin, y_pred_bin, average='binary', pos_label=pos_label)

# --- Ejemplo de uso para todos los modelos ---
for i in range(1, 11):
    y_test = globals()[f'y{i}_test']
    y_pred = globals()[f'y{i}_pred']
    precision = precision_binaria(y_test, y_pred)
    print(f'Precisión Modelo {i} (binaria t vs f):', precision)

Precisión Modelo 1 (binaria t vs f): 0.0
Precisión Modelo 2 (binaria t vs f): 0.0
Precisión Modelo 3 (binaria t vs f): 0.0
Precisión Modelo 4 (binaria t vs f): 0.0
Precisión Modelo 5 (binaria t vs f): 0.0
Precisión Modelo 6 (binaria t vs f): 0.0
Precisión Modelo 7 (binaria t vs f): 0.0
Precisión Modelo 8 (binaria t vs f): 0.0
Precisión Modelo 9 (binaria t vs f): 0.0
Precisión Modelo 10 (binaria t vs f): 0.0


c:\Users\ghseb\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\ghseb\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\ghseb\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capita

In [37]:
from sklearn.metrics import precision_score

# Asegúrate de que las predicciones y las etiquetas reales estén en formato de texto (si es necesario)
y1_test = [str(y) for y in y1_test]
y1_pred = [str(y) for y in y1_pred]
y2_test = [str(y) for y in y2_test]
y2_pred = [str(y) for y in y2_pred]
y3_test = [str(y) for y in y3_test]
y3_pred = [str(y) for y in y3_pred]
y4_test = [str(y) for y in y4_test]
y4_pred = [str(y) for y in y4_pred]
y5_test = [str(y) for y in y5_test]
y5_pred = [str(y) for y in y5_pred]
y6_test = [str(y) for y in y6_test]
y6_pred = [str(y) for y in y6_pred]
y7_test = [str(y) for y in y7_test]
y7_pred = [str(y) for y in y7_pred]
y8_test = [str(y) for y in y8_test]
y8_pred = [str(y) for y in y8_pred]
y9_test = [str(y) for y in y9_test]
y9_pred = [str(y) for y in y9_pred]
y10_test = [str(y) for y in y10_test]
y10_pred = [str(y) for y in y10_pred]

# --- Modelo 1 ---
precision1 = precision_score(y1_test, y1_pred, average='micro')  # O 'macro', 'weighted'
print('\nPrecisión Modelo 1 (Micro):', precision1)

# --- Modelo 2 ---
precision2 = precision_score(y2_test, y2_pred, average='micro')  # O 'macro', 'weighted'
print('\nPrecisión Modelo 2 (Micro):', precision2)

# --- Modelo 3 ---
precision3 = precision_score(y3_test, y3_pred, average='micro')  # O 'macro', 'weighted'
print('\nPrecisión Modelo 3 (Micro):', precision3)

# --- Modelo 4 ---
precision4 = precision_score(y4_test, y4_pred, average='micro')  # O 'macro', 'weighted'
print('\nPrecisión Modelo 4 (Micro):', precision4)

# --- Modelo 5 ---
precision5 = precision_score(y5_test, y5_pred, average='micro')  # O 'macro', 'weighted'
print('\nPrecisión Modelo 5 (Micro):', precision5)

# --- Modelo 6 ---
precision6 = precision_score(y6_test, y6_pred, average='micro')  # O 'macro', 'weighted'
print('\nPrecisión Modelo 6 (Micro):', precision6)

# --- Modelo 7 ---
precision7 = precision_score(y7_test, y7_pred, average='micro')  # O 'macro', 'weighted'
print('\nPrecisión Modelo 7 (Micro):', precision7)

# --- Modelo 8 ---
precision8 = precision_score(y8_test, y8_pred, average='micro')  # O 'macro', 'weighted'
print('\nPrecisión Modelo 8 (Micro):', precision8)

# --- Modelo 9 ---
precision9 = precision_score(y9_test, y9_pred, average='micro')  # O 'macro', 'weighted'
print('\nPrecisión Modelo 9 (Micro):', precision9)

# --- Modelo 10 ---
precision10 = precision_score(y10_test, y10_pred, average='micro')  # O 'macro', 'weighted'
print('\nPrecisión Modelo 10 (Micro):', precision10)



Precisión Modelo 1 (Micro): 0.0

Precisión Modelo 2 (Micro): 0.0

Precisión Modelo 3 (Micro): 0.3757062146892655

Precisión Modelo 4 (Micro): 0.8983050847457628

Precisión Modelo 5 (Micro): 0.0

Precisión Modelo 6 (Micro): 0.3531073446327684

Precisión Modelo 7 (Micro): 0.8983050847457628

Precisión Modelo 8 (Micro): 0.0

Precisión Modelo 9 (Micro): 0.3389830508474576

Precisión Modelo 10 (Micro): 0.8954802259887006


In [39]:
# Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

#exactitud = accuracy_score(y_test, y_pred)
#print('Exactitud del modelo:')
#print(exactitud)


#from sklearn.metrics import accuracy_score

# Calculamos la exactitud para cada modelo:

# --- Modelo 1 ---
exactitud1 = accuracy_score(y1_test, y1_pred)
print('\nExactitud Modelo 1:', exactitud1)

# --- Modelo 2 ---
exactitud2 = accuracy_score(y2_test, y2_pred)
print('\nExactitud Modelo 2:', exactitud2)

# --- Modelo 3 ---
exactitud3 = accuracy_score(y3_test, y3_pred)
print('\nExactitud Modelo 3:', exactitud3)

# --- Modelo 4 ---
exactitud4 = accuracy_score(y4_test, y4_pred)
print('\nExactitud Modelo 4:', exactitud4)

# --- Modelo 5 ---
exactitud5 = accuracy_score(y5_test, y5_pred)
print('\nExactitud Modelo 5:', exactitud5)

# --- Modelo 6 ---
exactitud6 = accuracy_score(y6_test, y6_pred)
print('\nExactitud Modelo 6:', exactitud6)

# --- Modelo 7 ---
exactitud7 = accuracy_score(y7_test, y7_pred)
print('\nExactitud Modelo 7:', exactitud7)

# --- Modelo 8 ---
exactitud8 = accuracy_score(y8_test, y8_pred)
print('\nExactitud Modelo 8:', exactitud8)

# --- Modelo 9 ---
exactitud9 = accuracy_score(y9_test, y9_pred)
print('\nExactitud Modelo 9:', exactitud9)

# --- Modelo 10 ---
exactitud10 = accuracy_score(y10_test, y10_pred)
print('\nExactitud Modelo 10:', exactitud10)


Exactitud Modelo 1: 0.0

Exactitud Modelo 2: 0.0

Exactitud Modelo 3: 0.3757062146892655

Exactitud Modelo 4: 0.8983050847457628

Exactitud Modelo 5: 0.0

Exactitud Modelo 6: 0.3531073446327684

Exactitud Modelo 7: 0.8983050847457628

Exactitud Modelo 8: 0.0

Exactitud Modelo 9: 0.3389830508474576

Exactitud Modelo 10: 0.8954802259887006


In [40]:
# Verificar la distribución de clases en y_test y y_pred
from collections import Counter

print("Distribución en y1_test:", Counter(y1_test))
print("Distribución en y1_pred:", Counter(y1_pred))

Distribución en y1_test: Counter({'0.0': 223, '1.0': 131})
Distribución en y1_pred: Counter({'1': 354})


In [42]:
from sklearn.linear_model import LogisticRegression
from collections import Counter
from sklearn.metrics import recall_score

# Definir el modelo con balanceo de clases (para manejar desequilibrio)
modelo = LogisticRegression(class_weight='balanced', random_state=42)

# Entrenar el modelo con tus datos del Modelo 1
modelo.fit(X1_train, y1_train)

# Obtener probabilidades para la clase 'f' (asumiento que es la clase minoritaria)
y1_pred_prob = modelo.predict_proba(X1_test)[:, 1]  # Probabilidades de la clase 'f'

# Ajustar el umbral de decisión (empieza con 0.3 y ajusta según necesidad)
umbral = 0.3  # Puedes probar con 0.4, 0.2, etc.
y1_pred_ajustado = ['f' if prob >= umbral else 't' for prob in y1_pred_prob]

# Verificar distribución de predicciones
print("\nDistribución en y1_test (real):", Counter(y1_test))
print("Distribución en y1_pred_ajustado:", Counter(y1_pred_ajustado))

# Calcular métricas de recall (sensibilidad ajustada)
sensibilidad1_ajustada = recall_score(y1_test, y1_pred_ajustado, average='micro', pos_label='f')
print("\nSensibilidad ajustada (Recall para 'f'):", sensibilidad1_ajustada)



Distribución en y1_test (real): Counter({'0.0': 223, '1.0': 131})
Distribución en y1_pred_ajustado: Counter({'f': 353, 't': 1})

Sensibilidad ajustada (Recall para 'f'): 0.0


c:\Users\ghseb\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1618: UserWarning: Note that pos_label (set to 'f') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


In [44]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import recall_score

# Modelo con balanceo de clases
modelo = LogisticRegression(class_weight='balanced', random_state=42)
modelo.fit(X1_train, y1_train)

# Predicciones con umbral ajustado
y1_pred_prob = modelo.predict_proba(X1_test)[:, 1]  # Probabilidad de 'f'
umbral = 0.3  # Ajusta según necesidad
y1_pred_ajustado = ['f' if prob >= umbral else 't' for prob in y1_pred_prob]

# Sensibilidad corregida
sensibilidad = recall_score(y1_test, y1_pred_ajustado, average='micro', pos_label='f')
print("Sensibilidad ajustada:", sensibilidad)


Sensibilidad ajustada: 0.0


c:\Users\ghseb\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1618: UserWarning: Note that pos_label (set to 'f') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


In [46]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import recall_score
from collections import Counter

# Listas de datos de entrenamiento y prueba para cada modelo
X_train_list = [X1_train, X2_train, X3_train, X4_train, X5_train, X6_train, X7_train, X8_train, X9_train, X10_train]
y_train_list = [y1_train, y2_train, y3_train, y4_train, y5_train, y6_train, y7_train, y8_train, y9_train, y10_train]
X_test_list = [X1_test, X2_test, X3_test, X4_test, X5_test, X6_test, X7_test, X8_test, X9_test, X10_test]
y_test_list = [y1_test, y2_test, y3_test, y4_test, y5_test, y6_test, y7_test, y8_test, y9_test, y10_test]

# Umbral ajustado
umbral = 0.3

# Iterar sobre los modelos
for i, (X_train, y_train, X_test, y_test) in enumerate(zip(X_train_list, y_train_list, X_test_list, y_test_list), start=1):
    # Crear y entrenar el modelo
    modelo = LogisticRegression(class_weight='balanced', random_state=42)
    modelo.fit(X_train, y_train)
    
    # Predicciones con umbral ajustado
    y_pred_prob = modelo.predict_proba(X_test)[:, 1]  # Probabilidad de 'f'
    y_pred_ajustado = ['f' if prob >= umbral else 't' for prob in y_pred_prob]
    
    # Calcular sensibilidad
    sensibilidad = recall_score(y_test, y_pred_ajustado, average='micro', pos_label='f')
    print(f"Sensibilidad Modelo {i}:", sensibilidad)


Sensibilidad Modelo 1: 0.0
Sensibilidad Modelo 2: 0.0
Sensibilidad Modelo 3: 0.0
Sensibilidad Modelo 4: 0.0
Sensibilidad Modelo 5: 0.0
Sensibilidad Modelo 6: 0.0
Sensibilidad Modelo 7: 0.0
Sensibilidad Modelo 8: 0.0
Sensibilidad Modelo 9: 0.0
Sensibilidad Modelo 10: 0.0


c:\Users\ghseb\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1618: UserWarning: Note that pos_label (set to 'f') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
c:\Users\ghseb\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1618: UserWarning: Note that pos_label (set to 'f') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
c:\Users\ghseb\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1618: UserWarning: Note that pos_label (set to 'f') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
c:\Users\ghseb\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1618: U

**reemplazar los valores**

In [48]:
#verificar los valores sin repetir
#unico=np.unique(df['class'])
#unico

# Verificar los valores únicos en las variables dependientes definidas
variables_dependientes = [Var_Dep1, Var_Dep2, Var_Dep3, Var_Dep4, Var_Dep5, Var_Dep6, Var_Dep7, Var_Dep8, Var_Dep9, Var_Dep10]

for i, var_dep in enumerate(variables_dependientes, start=1):
    unico = np.unique(var_dep)
    print(f"Valores únicos en Var_Dep{i}: {unico}")

Valores únicos en Var_Dep1: [0. 1.]
Valores únicos en Var_Dep2: [0. 1.]
Valores únicos en Var_Dep3: [0 1]
Valores únicos en Var_Dep4: [0 1]
Valores únicos en Var_Dep5: [0. 1.]
Valores únicos en Var_Dep6: [0 1]
Valores únicos en Var_Dep7: [0 1]
Valores únicos en Var_Dep8: [0. 1.]
Valores únicos en Var_Dep9: [0 1]
Valores únicos en Var_Dep10: [0 1]
